# Generated by Django 2.2.3 on 2019-07-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nelayan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('umur', models.CharField(max_length=50)),
                ('distrik', models.CharField(max_length=50)),
                ('kampung', models.CharField(max_length=50)),
            ],
        ),
    ]
